"""add exercise_order to WorkoutExerciseWorkoutOrderLink

Revision ID: 048e115a5d4e
Revises: acc1f5dd0043
Create Date: 2024-05-12 11:52:46.014401

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '048e115a5d4e'
down_revision: Union[str, None] = 'acc1f5dd0043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workoutexerciseworkoutorderlink', 'exercise_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_workoutexerciseworkoutorderlink_exercise_order'), 'workoutexerciseworkoutorderlink', ['exercise_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workoutexerciseworkoutorderlink_exercise_order'), table_name='workoutexerciseworkoutorderlink')
    op.alter_column('workoutexerciseworkoutorderlink', 'exercise_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
