"""modify workout exercise model and table

Revision ID: 0a7c944dc2ca
Revises: c58f2d7cca45
Create Date: 2024-05-05 13:14:05.299737

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7c944dc2ca'
down_revision: Union[str, None] = 'c58f2d7cca45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workoutexercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planned_sets', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('planned_reps', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('planned_resistance_weight', sa.Float(), nullable=False))
        batch_op.drop_column('resistance_type')
        batch_op.drop_column('reps')
        batch_op.drop_column('sets')
        batch_op.drop_column('resistance_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workoutexercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resistance_weight', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('sets', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('reps', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('resistance_type', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('planned_resistance_weight')
        batch_op.drop_column('planned_reps')
        batch_op.drop_column('planned_sets')
    # ### end Alembic commands ###
