"""add user_uuid to workout_exercise

Revision ID: 15508864446a
Revises: 0a7c944dc2ca
Create Date: 2024-05-05 15:45:40.015382

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
import models.utility


# revision identifiers, used by Alembic.
revision: str = '15508864446a'
down_revision: Union[str, None] = '0a7c944dc2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workoutexercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_uuid', models.utility.GUID(), nullable=True))
        batch_op.create_foreign_key('fk_workout_exercise', 'user', ['user_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workoutexercise', schema=None) as batch_op:
        batch_op.drop_constraint('fk_workout_exercise', type_='foreignkey')
        batch_op.drop_column('user_uuid')
    # ### end Alembic commands ###
