"""add cascade to category ids in exercise

Revision ID: 5594e85862ab
Revises: 048e115a5d4e
Create Date: 2024-05-13 18:53:17.828539

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5594e85862ab'
down_revision: Union[str, None] = '048e115a5d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exercise_workout_category_id_fkey', 'exercise', type_='foreignkey')
    op.drop_constraint('exercise_equipment_id_fkey', 'exercise', type_='foreignkey')
    op.drop_constraint('exercise_movement_category_id_fkey', 'exercise', type_='foreignkey')
    op.drop_constraint('exercise_major_muscle_id_fkey', 'exercise', type_='foreignkey')
    op.drop_constraint('exercise_user_id_fkey', 'exercise', type_='foreignkey')
    op.create_foreign_key(None, 'exercise', 'equipment', ['equipment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exercise', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exercise', 'workoutcategory', ['workout_category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exercise', 'movementcategory', ['movement_category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exercise', 'majormuscle', ['major_muscle_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.drop_constraint(None, 'exercise', type_='foreignkey')
    op.create_foreign_key('exercise_user_id_fkey', 'exercise', 'user', ['user_id'], ['id'])
    op.create_foreign_key('exercise_major_muscle_id_fkey', 'exercise', 'majormuscle', ['major_muscle_id'], ['id'])
    op.create_foreign_key('exercise_movement_category_id_fkey', 'exercise', 'movementcategory', ['movement_category_id'], ['id'])
    op.create_foreign_key('exercise_equipment_id_fkey', 'exercise', 'equipment', ['equipment_id'], ['id'])
    op.create_foreign_key('exercise_workout_category_id_fkey', 'exercise', 'workoutcategory', ['workout_category_id'], ['id'])
    # ### end Alembic commands ###
