"""add custom exercise id to workoutexercise

Revision ID: 9033892ae186
Revises: d76ae5c093ae
Create Date: 2024-05-08 21:24:11.631421

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9033892ae186'
down_revision: Union[str, None] = 'd76ae5c093ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workoutexercise', sa.Column('custom_exercise_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_workoutexercise_custom_exercise_id'), 'workoutexercise', ['custom_exercise_id'], unique=False)
    op.create_foreign_key(None, 'workoutexercise', 'customexercise', ['custom_exercise_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workoutexercise', type_='foreignkey')
    op.drop_index(op.f('ix_workoutexercise_custom_exercise_id'), table_name='workoutexercise')
    op.drop_column('workoutexercise', 'custom_exercise_id')
    # ### end Alembic commands ###
