"""add user role link

Revision ID: a179dacc27d7
Revises: 32c04ebca1cd
Create Date: 2024-05-09 14:54:21.665974

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a179dacc27d7'
down_revision: Union[str, None] = '32c04ebca1cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userrolelink',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index(op.f('ix_userrolelink_role_id'), 'userrolelink', ['role_id'], unique=False)
    op.create_index(op.f('ix_userrolelink_user_id'), 'userrolelink', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userrolelink_user_id'), table_name='userrolelink')
    op.drop_index(op.f('ix_userrolelink_role_id'), table_name='userrolelink')
    op.drop_table('userrolelink')
    # ### end Alembic commands ###
