"""reconfigure link between workout and workout_exercise with an exercise_order id

Revision ID: acc1f5dd0043
Revises: 2cfc4430395c
Create Date: 2024-05-10 17:30:16.513847

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc1f5dd0043'
down_revision: Union[str, None] = '2cfc4430395c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workoutexerciseworkoutorderlink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=False),
    sa.Column('exercise_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workoutexercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'workout_exercise_id')
    )
    op.create_index(op.f('ix_workoutexerciseworkoutorderlink_id'), 'workoutexerciseworkoutorderlink', ['id'], unique=False)
    op.create_index(op.f('ix_workoutexerciseworkoutorderlink_workout_exercise_id'), 'workoutexerciseworkoutorderlink', ['workout_exercise_id'], unique=False)
    op.create_index(op.f('ix_workoutexerciseworkoutorderlink_workout_id'), 'workoutexerciseworkoutorderlink', ['workout_id'], unique=False)
    op.drop_index('ix_workoutexercise_exercise_order', table_name='workoutexercise')
    op.drop_index('ix_workoutexercise_workout_id', table_name='workoutexercise')
    op.drop_constraint('workoutexercise_workout_id_fkey', 'workoutexercise', type_='foreignkey')
    op.drop_column('workoutexercise', 'workout_id')
    op.drop_column('workoutexercise', 'exercise_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workoutexercise', sa.Column('exercise_order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('workoutexercise', sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('workoutexercise_workout_id_fkey', 'workoutexercise', 'workout', ['workout_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_workoutexercise_workout_id', 'workoutexercise', ['workout_id'], unique=False)
    op.create_index('ix_workoutexercise_exercise_order', 'workoutexercise', ['exercise_order'], unique=False)
    op.drop_index(op.f('ix_workoutexerciseworkoutorderlink_workout_id'), table_name='workoutexerciseworkoutorderlink')
    op.drop_index(op.f('ix_workoutexerciseworkoutorderlink_workout_exercise_id'), table_name='workoutexerciseworkoutorderlink')
    op.drop_index(op.f('ix_workoutexerciseworkoutorderlink_id'), table_name='workoutexerciseworkoutorderlink')
    op.drop_table('workoutexerciseworkoutorderlink')
    # ### end Alembic commands ###
