"""add user_uuid to Workout

Revision ID: c58f2d7cca45
Revises: 
Create Date: 2024-05-05 13:01:14.470366

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
import models.utility


# revision identifiers, used by Alembic.
revision: str = 'c58f2d7cca45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_uuid', models.utility.GUID(), nullable=True))
        batch_op.create_foreign_key('fk_workout_user', 'user', ['user_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout') as batch_op:
        batch_op.drop_constraint(None, 'workout', type_='foreignkey')
        batch_op.drop_column('workout', 'user_uuid')
    # ### end Alembic commands ###
