"""add custom exercise

Revision ID: d76ae5c093ae
Revises: b1543aaebea0
Create Date: 2024-05-08 11:39:20.776679

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
import models.utility


# revision identifiers, used by Alembic.
revision: str = 'd76ae5c093ae'
down_revision: Union[str, None] = 'b1543aaebea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customexercise',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', models.utility.GUID(), nullable=True),
    sa.Column('workout_category_id', sa.Integer(), nullable=True),
    sa.Column('movement_category_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('major_muscle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['major_muscle_id'], ['majormuscle.id'], ),
    sa.ForeignKeyConstraint(['movement_category_id'], ['movementcategory.id'], ),
    sa.ForeignKeyConstraint(['workout_category_id'], ['workoutcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customexercise_equipment_id'), 'customexercise', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_customexercise_id'), 'customexercise', ['id'], unique=False)
    op.create_index(op.f('ix_customexercise_major_muscle_id'), 'customexercise', ['major_muscle_id'], unique=False)
    op.create_index(op.f('ix_customexercise_movement_category_id'), 'customexercise', ['movement_category_id'], unique=False)
    op.create_index(op.f('ix_customexercise_uuid'), 'customexercise', ['uuid'], unique=True)
    op.create_index(op.f('ix_customexercise_workout_category_id'), 'customexercise', ['workout_category_id'], unique=False)
    op.create_table('customexercisespecificmusclelink',
    sa.Column('custom_exercise_id', sa.Integer(), nullable=False),
    sa.Column('specific_muscle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_exercise_id'], ['customexercise.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specific_muscle_id'], ['specificmuscle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('custom_exercise_id', 'specific_muscle_id')
    )
    op.create_index(op.f('ix_customexercisespecificmusclelink_custom_exercise_id'), 'customexercisespecificmusclelink', ['custom_exercise_id'], unique=False)
    op.create_index(op.f('ix_customexercisespecificmusclelink_specific_muscle_id'), 'customexercisespecificmusclelink', ['specific_muscle_id'], unique=False)
    op.add_column('exerciselog', sa.Column('custom_exercise_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_exerciselog_custom_exercise_id'), 'exerciselog', ['custom_exercise_id'], unique=False)
    op.create_foreign_key(None, 'exerciselog', 'customexercise', ['custom_exercise_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exerciselog', type_='foreignkey')
    op.drop_index(op.f('ix_exerciselog_custom_exercise_id'), table_name='exerciselog')
    op.drop_column('exerciselog', 'custom_exercise_id')
    op.drop_index(op.f('ix_customexercisespecificmusclelink_specific_muscle_id'), table_name='customexercisespecificmusclelink')
    op.drop_index(op.f('ix_customexercisespecificmusclelink_custom_exercise_id'), table_name='customexercisespecificmusclelink')
    op.drop_table('customexercisespecificmusclelink')
    op.drop_index(op.f('ix_customexercise_workout_category_id'), table_name='customexercise')
    op.drop_index(op.f('ix_customexercise_uuid'), table_name='customexercise')
    op.drop_index(op.f('ix_customexercise_movement_category_id'), table_name='customexercise')
    op.drop_index(op.f('ix_customexercise_major_muscle_id'), table_name='customexercise')
    op.drop_index(op.f('ix_customexercise_id'), table_name='customexercise')
    op.drop_index(op.f('ix_customexercise_equipment_id'), table_name='customexercise')
    op.drop_table('customexercise')
    # ### end Alembic commands ###
