"""update exercise_log table fields

Revision ID: e2493571b421
Revises: 
Create Date: 2024-04-29 16:15:08.694943

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2493571b421'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exerciselog', 'sets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exerciselog', sa.Column('sets', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
